version: '2'

# Go task : https://taskfile.org

vars:
  API_URL:
    sh: aws cloudformation describe-stacks --stack-name {{.STACK_NAME}} --query 'Stacks[0].Outputs[?OutputKey==`ApigwURL`].OutputValue' --output text

tasks:
  validate:
    desc: Validate Cloudformation syntax
    cmds:
      - sam validate --template {{.TEMPLATE}}

  build:
    desc: Build Cloudformation template
    deps:
      - validate
    cmds:
      - sam build --use-container --template {{.TEMPLATE}} --debug --manifest requirements.txt

  package:
    desc: transform and package cloudfomartion template to Amazon S3
    deps: []
    cmds:
      - aws cloudformation package --s3-bucket {{.S3_BUCKET}} --template {{.TEMPLATE}} --output-template-file packaged.yaml

  deploy:
    desc: Deploy cloudformation template
    deps: [package,validate]
    cmds:
      - aws cloudformation deploy --s3-bucket {{.S3_BUCKET}} --template-file packaged.yaml --capabilities CAPABILITY_IAM --stack-name {{.STACK_NAME}}

  logtail:
    cmds:
      - sam logs -n {{.LAMBDA}} --stack-name {{.STACK_NAME}} --tail

  local-api:
    desc: Run local API
    cmds:
      - sam local start-api --template {{.TEMPLATE}}
    env:
      TABLE_NAME: '{{.DDB_TABLE}}'
  
  load-test:
    desc: load test the API
    cmds:
    - locust -f loadtest/locustfile.py --host={{.API_URL}} --clients=200 --hatch-rate=10 --no-web --run-time 5m