version: '2'

# Go task : https://taskfile.org

vars:
  S3_BUCKET: gma-test
  STACK_NAME: aws-sam-ws-python-stack
  TEMPLATE: template.yml

tasks:
  validate:
    desc: Validate Cloudformation syntax
    cmds:
      - sam validate --template {{.TEMPLATE}}

  package:
    desc: transform and package cloudfomartion template to Amazon S3
    deps: []
    cmds:
      - sam package --s3-bucket {{.S3_BUCKET}} --output-template-file packaged.yaml

  deploy:
    desc: Deploy cloudformation template
    deps: [package,validate]
    cmds:
      - sam deploy --s3-bucket {{.S3_BUCKET}} --template-file packaged.yaml --capabilities CAPABILITY_IAM --stack-name {{.STACK_NAME}}

  logtail:
    cmds:
      - sam logs -n {{.LAMBDA}} --stack-name {{.STACK_NAME}} --tail

  local-api:
    desc: Run local API
    cmds:
      - sam local start-api --template {{.TEMPLATE}}
    env:
      TABLE_NAME: HelloTable
 
