AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:

  HelloWorldGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.get
      Runtime: python3.6
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: HelloTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: '/{name}'
            Method: get
      Description: HelloWorld Get Function

  HelloWorldList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.list
      Runtime: python3.6
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: HelloTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      Description: HelloWorld List Function

      
  HelloWorldPost:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.post
      Runtime: python3.6
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: HelloTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: HelloTable
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: '/{name}'
            Method: post
      Description: HelloWorld Post Function

  HelloTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: name
        Type: String

Outputs:
  ApigwURL:
    Description: API Gateway endpoint URL
    Value:
      'Fn::Sub': >-
        https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
