AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
      Description: HelloWorld Function
Outputs:
  ApigwURL:
    Description: API Gateway endpoint URL
    Value:
      'Fn::Sub': >-
        https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  HelloWorldFunction:
    Description: HelloWorld Function ARN
    Value:
      'Fn::GetAtt':
        - HelloWorld
        - Arn
